### PR TITLE
Add additional list functions to reach parity with RESTful list requests

### PR DESCRIPTION
**Pull request by rasharab**
## Problem

https://github.com/pinecone-io/pinecone-java-client/issues/126

## Solution

With REST, we are currently able to list vectors without a prefix but with a pagination token.
This is not currently available with v1 of the pinecone-java-client.

With this PR, we have added a function list with a pagination token and limit but no prefix.

### CODE REVIEW

**Review by rohanshah18 — CHANGES_REQUESTED** [review]
Thanks for taking time to create this PR. Would you please:
1. add the same method to the AsyncIndex?
https://github.com/pinecone-io/pinecone-java-client/blob/main/src/main/java/io/pinecone/clients/AsyncIndex.java
2. add tests here for both Index and AsyncIndex methods:
https://github.com/pinecone-io/pinecone-java-client/blob/main/src/integration/java/io/pinecone/integration/dataPlane/ListEndpointTest.java

**Comment by rasharab** [comment]
Absolutely!

**Comment by rasharab** [comment]
Done!
Thanks @rohanshah18

**Comment by rohanshah18** [comment]
@rasharab Sorry I was out all of this week for a company event but I'm more than happy to run the integration tests and release this PR if you still need it

**Comment by rasharab** [comment]
Please release it. Thank you!

**Comment by rohanshah18** [comment]
Would you please open the PR again so I can run the integration test, verify the correctness, and merge it in.

**Comment by rasharab** [comment]
Sorry, one of our engineers deleted our fork. :(
I'll handle this, apologies.

**Comment by rasharab** [comment]
annoyingly, had to re-create pr...

https://github.com/pinecone-io/pinecone-java-client/pull/133

**Comment by rohanshah18** [comment]
Ok thanks, taking a look

**Pull request closed without merging**
